### ISSUE TITLE
Remove reliance on go-open-service-broker-client

### ISSUE THREAD

**Issue by jmrodri** [pmorie/osb-broker-lib#20]
I think the `osb-broker-lib` should not rely on the `go-open-service-broker-client`. If anything the client should depend on the broker-lib for its data types. It feels weird to have a broker depend on a client.

**Comment by pmorie** [comment]
I do not want to create a project that has both client and broker. Keeping the repositories separate allows us to independently iterate on things and give users the best options for reacting to things like breaking changes. I don’t want to introduce yet another project for the types because it’s one more dependency to track.

It might seem weird to have a broker depend on the client, but remember - the broker has to do what the platform (the client) expects. If you think about it that way it’s not quite as weird. The most important thing is that the broker and platform share the same definition of the contract.
